services:
  api:
    image: bouzomgi/chatter-be
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - AWS_S3_URL_SIGNER_ENDPOINT=${AWS_S3_URL_SIGNER_ENDPOINT}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - FRONTEND_ENDPOINT=${FRONTEND_ENDPOINT}
    ports:
      - "4000:4000"
    volumes:
      - ./private/cert:/private/cert:ro
    networks:
      - chatter-network

networks:
  chatter-network:
    external: true