openapi: 3.0.0
info:
  title: Chatter REST API Docs
  version: 1.0.0
  description: This is a simple CRUD API application made with Express and documented with Swagger
tags: 
  - name: general
  - name: authentication
  - name: settings
  - name: chat
paths:
  /api/health:
    get:
      tags: 
        - general
      summary: Health check
      responses:
        "200":
          $ref: '#/components/responses/Ok'

  /api/register:
    post:
      tags: 
        - authentication
      summary: Register a new User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: mike@gmail.com
                username:
                  type: string
                  example: mike11
                password:
                  type: string
                  example: password123
                  minLength: 5
              required:
                - email
                - username
                - password
      responses:
        "201":
          $ref: '#/components/responses/Created'

        "400":
          $ref: '#/components/responses/BadRequest'

  /api/login:
    post:
      tags: 
        - authentication
      summary: Login as a User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: mike11
                password:
                  type: string
                  example: password123
              required:
                - username
                - password
      responses:
        "200":
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'

        "400":
          $ref: '#/components/responses/BadRequest'
          
        "401":
          $ref: '#/components/responses/Unauthorized'
          
  /api/logout:
    post:
      tags:
        - authentication
      summary: Logout the current User
      security:
        - jwtAuth: []
      responses:
        "200":
          $ref: '#/components/responses/Ok'

  /api/authed/defaultAvatars:
    get:
      tags: 
        - settings
      summary: Get default avatars and the user's current avatar
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Default avatars and current avatar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Avatar'

        "400":
          $ref: '#/components/responses/BadRequest'
 
        "401":
          $ref: '#/components/responses/Unauthorized'

  /api/authed/setSettings:
    post:
      tags: 
        - settings
      summary: Set settings for a User
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  example: 'avatar-1'
      responses:
        "200":
          $ref: '#/components/responses/Ok'

        "400":
          $ref: '#/components/responses/BadRequest'

        "401":
          $ref: '#/components/responses/Unauthorized'

        "404":
          $ref: '#/components/responses/NotFound'
  
  /api/authed/userHeads:
    get:
      tags: 
        - chat
      summary: Get all other users
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Successfully got user heads
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserHead'

        "400":
          $ref: '#/components/responses/BadRequest'

        "401":
          $ref: '#/components/responses/Unauthorized'
          
  /api/authed/chats:
    get:
      tags: 
        - chat
      summary: Get all chats the user is part of
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Successfully got messages
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Chat'

        "401":
          $ref: '#/components/responses/Unauthorized'
          
        "500":
          $ref: '#/components/responses/InternalServerError'


  /api/authed/chatUsersDetails:
    get:
      tags: 
        - chat
      summary: Get details of all users chatting with a given user
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Successfully got details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetails'

        "400":
          $ref: '#/components/responses/BadRequest'
      
        "401":
          $ref: '#/components/responses/Unauthorized'



  /api/authed/message:
    post:
      tags: 
        - chat
      summary: Send a message to a specified chat thread
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                members:
                  $ref: '#/components/schemas/ChatMembers'
                content:
                  example: "lorem ipsum"
                  type: string
              required:
                - members
                - content
  
      responses:
        "201":
          description: Successfully sent message
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ChatDetails'
                  - type: object
                    properties:
                      message:
                        $ref: '#/components/schemas/Message'
                    required:
                      - message

        "400":
          $ref: '#/components/responses/BadRequest'
      
        "401":
          $ref: '#/components/responses/Unauthorized'

  /api/authed/readThread/{threadId}:
    patch:
      tags: 
        - chat
      summary: Mark a specified thread as read
      security:
        - jwtAuth: []
      parameters:
        - name: threadId
          in: path
          required: true
          description: ID of the thread to be marked as read
          schema:
            type: string
      responses:
        "200":
          $ref: '#/components/responses/Ok'

        "400":
          $ref: '#/components/responses/BadRequest'

        "401":
          $ref: '#/components/responses/Unauthorized'

        "404":
          $ref: '#/components/responses/NotFound'
                      
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    Avatar:
      type: object
      properties:
        name:
          type: string
          example: "avatar-1"
        url:
          type: string
          example: "www.avatar-1.com"
      required:
        - name
        - url

    ChatMembers:
      type: array
      items:
        type: number
      minimum: 2
      example: [1, 2]
      
    UserDetails:
      type: object
      properties:
        userId: 
          type: number
          example: 1
        username: 
          type: string
          example: 'mike11'
        avatar: 
          $ref: '#/components/schemas/Avatar'
      required:
        - userId
        - username
        - avatar
        
    UserHead:
      allOf:
        - $ref: '#/components/schemas/UserDetails'
        - type: object
          properties:
            threadId:
              type: number
              example: 1

    Message:
      type: object
      properties:
        messageId:
          type: number
          example: 1
        fromUserId:
          type: number
          example: 1
        createdAt:
          type: string
          example: '2024-03-15T10:01:00Z'
        content:
          type: string
          example: 'lorem ipsum'
      required:
        - messageId
        - fromUserId
        - createdAt
        - content
    
    ChatDetails:
      type: object
      properties:
        conversationId:
          type: number
          example: 1
        threadId: 
          type: number
          example: 1
        members:
          $ref: '#/components/schemas/ChatMembers'
        unseenMessageId: 
          type: number
          example: 1
      required:
        - conversationId
        - threadId
        - members

    Chat:
      allOf:
        - $ref: '#/components/schemas/ChatDetails'
        - type: object
          properties:
            messages:
              type: array
              items:
                $ref: '#/components/schemas/Message'
          required:
            - messages
    
  responses:
    Ok:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Request was successful."
            required: 
              - message
    Created:
      description: Resource created successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Resource created successfully."
            required: 
              - message
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid request."
            required: 
              - error
    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Authentication is required."
            required: 
              - error
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Resource not found."
            required: 
              - error

    InternalServerError:
      description: Server cannot process request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Server could not process."
            required: 
              - error