name: 'PR'
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-code:
    environment: test
    env:
      PORT: 3000

    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Lint
        run: npm run check-lint

      - name: Run Tests and Code Coverage
        run: npm test

      - name: Set status
        run: echo "status=$([ "${{ job.status }}" == "success" ] && echo "CI-${GITHUB_RUN_ID}-success" || echo "CI-${GITHUB_RUN_ID}-failure")" >> $GITHUB_ENV

